---
name: release-please

'on':
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: kitchen-digitalocean
          version-file: lib/kitchen/driver/digitalocean_version.rb

      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Build and publish to GitHub Package
        uses: jstastny/publish-gem-to-github@master
        if: ${{ steps.release.outputs.release_created }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ secrets.OWNER }}

      - name: Build and publish to RubyGems
        uses: actionshub/publish-gem-to-rubygems@main
        if: ${{ steps.release.outputs.release_created }}
        env:
          token: ${{ secrets.RUBYGEMS_TOKEN }}
          owner: ${{ secrets.OWNER }}
